// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avepcjpvqnlgrjjvcxji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2ZXBjanB2cW5sZ3JqanZjeGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzEyNDIsImV4cCI6MjA2MDEwNzI0Mn0.a4nv0_nCvBh6VkLik7TuwDZhRcUscD4b88QdEVFOg9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);